final:

	g++ -c graphics_and_engine.cpp
	g++ -c main.cpp
	g++ graphics_and_engine.o main.o -o main -lsfml-graphics -lsfml-window -lsfml-system

game:

	g++ -c graphics_and_engine.cpp
	g++ -c main.cpp
	g++ graphics_and_engine.o main.o -o main -lsfml-graphics -lsfml-window -lsfml-system
	./main

